### ISSUE TITLE
RAG optimization: overwritten database

### ISSUE THREAD

**Issue by AntoniaJost** [CliDyn/climsight#116]
Right now, when one (or multiple) file(s) in ```data/ipcc_text_reports```  have changed, the entire chunking and embedding will take place again and get added on top of the already existing chunks, even if they already exist. 
Desired behaviour: only the file(s) that has/have changed or were newly added shall get chunked and embedded to save resources.

**Comment by kuivi** [comment]
We do not need to check if the source files for IPCC or other reports have changed at the start of ClimSight. Instead, ClimSight should only verify whether the RAG db exists. The db generation should be handled separately, and the database should be uploaded to the server for downloading during installation.

Therefore, a separate Python script is required to regenerate the database when necessary. Additionally, there is no need to download IPCC source files for normal use; only the database should be downloaded.

For comparing source files (if necessary), use a “checksum,” such as the one provided by the hashlib.

**Comment by AntoniaJost** [comment]
closed by #125
