### ISSUE TITLE
RAG

### ISSUE THREAD

**Issue by kuivi** [CliDyn/climsight#122]
We do not need to check if the source files for IPCC or other reports have changed at the start of ClimSight. Instead, ClimSight should only verify whether the RAG db exists. The db generation should be handled separately, and the database should be uploaded to the server for downloading during installation.

Therefore, a separate Python script is required to regenerate the database when necessary. Additionally, there is no need to download IPCC source files for normal use; only the database should be downloaded.

For comparing source files (if necessary), use a “checksum,” such as the one provided by the hashlib.

some details:
remove inizialization and loading rag db from climsight.py:
https://github.com/CliDyn/climsight/blob/d1bf8341fd7d2f779451a9f29f4330a78a249ea0/src/climsight/climsight.py#L72
1. we do not need to check txt files.
2. we do not have api_key before calling streamlit and terminal interfaces.  

move load_rag to streamlit_interface : 
https://github.com/CliDyn/climsight/blob/d1bf8341fd7d2f779451a9f29f4330a78a249ea0/src/climsight/streamlit_interface.py#L86
and to terminal_interface
https://github.com/CliDyn/climsight/blob/d1bf8341fd7d2f779451a9f29f4330a78a249ea0/src/climsight/terminal_interface.py#L93

rename current rag to rag_ipcc, 

move ./rag_db to ./data/rag_db 

do not download ipcc_text_reports

download rag_db from server

we do not need last_update.txt

remove all global variables, transfer rag_ready, rag_db from func or save to data dict

**Comment by AntoniaJost** [comment]
Includes an issue that was already mentioned in #116. Adding it here so both get closed in the end.

**Comment by AntoniaJost** [comment]
I am hestiant to call it particularly "rag_ipcc" as I am just working on enlarging the sources in the database beyond IPCC but we can discuss something like "rag_files" or "rag_addSources".

**Comment by AntoniaJost** [comment]
@kuivi Just so we are on the same side: I would create a rag folder inside this repo and put a separate python file there that creates the db if called specifically but does not interact with climsight in any other way. Or were you thinking of an entire separate repo for this?

**Comment by kuivi** [comment]
Yes, that’s correct, just a separate folder for scripts.

**Comment by kuivi** [comment]
> I am hestiant to call it particularly "rag_ipcc" as I am just working on enlarging the sources in the database beyond IPCC but we can discuss something like "rag_files" or "rag_addSources".
Yes, it can be postponed until next week; it’s a matter of organizing the request. I think putting everything into one database might be too much; it’s better to split it into different databases (as we discussed by regions or languages). And either call them through different agents or within one agent but as different tools.

**Comment by AntoniaJost** [comment]
closed by #125
