### ISSUE TITLE
Add first tests

### ISSUE THREAD

**Issue by koldunovn** [CliDyn/climsight#16]

**Comment by koldunovn** [comment]
Think of how automatic testing should look like. It is not clear to me how to test weinterface - have a look how they do it on streamlit. We also probably have to mock recieving data from LLM somehow.

**Comment by AntoniaJost** [comment]
Handle exception if water is being clicked (and no address can be retrieved).

**Comment by AntoniaJost** [comment]
https://docs.streamlit.io/library/api-reference/app-testing

**Comment by AntoniaJost** [comment]
> Handle exception if water is being clicked (and no address can be retrieved).

This should not be an issue anymore after #31 and #(add PR number of osm branch once it's merged)
