### ISSUE TITLE
Demographic_Indicators

### ISSUE THREAD

**Issue by kuivi** [CliDyn/climsight#41]
I'm encountering a problem while attempting to download **WPP2022_Demographic_Indicators_Medium.zip** using the **download_data.sh** script.

It appears there's an issue with SSL negotiation, either on my side or with the server at population.un.org. If this issue is occurring on my machine, it's possible others may encounter the same problem. While the file can be downloaded via a browser (like HTTPS) without issues, the file size is approximately 7MB, which presents a dilemma: we could either directly upload it to GitHub (not advisable) or host it on an external server, such as https://swift.dkrz.de.

we anyway need to adapt download_data.sh and AWI-CM-1 data  on dkrz how @AntoniaJost  mention in [commit from 9 Feb](https://github.com/koldunovn/climsight/pull/32#issuecomment-1935702717)

**Comment by koldunovn** [comment]
I had no problems downloading the file. Downloading file via browser and putting it on GitHub is not an option. We can check the licens, and if it allows redistribution, we can add it to the archive we download from DKRZ together with AWI-CM data. @AntoniaJost can you check the license and see if we have right to redistribute the data?
