### ISSUE TITLE
Move from wget to curl for downloading files

### ISSUE THREAD

**Issue by koldunovn** [CliDyn/climsight#43]
The `wget` is not a standard package on MacOS, while `curl` is.

**Comment by kuivi** [comment]
As an option: download all files via Python as a separate miniscript, with checks on file checksums, only if there are simple built-in Python download methods available.

**Comment by koldunovn** [comment]
> As an option: download all files via Python as a separate miniscript, with checks on file checksums, only if there are simple built-in Python download methods available.

This will be system independent also :)

**Comment by AntoniaJost** [comment]
While doing this, a timeout for the data download should be added. For me, the download always runs into eternity while trying to download the land and river zip files. Accordingly, the exception of not having downloaded this data should be integrated into geo_functions.py
