### ISSUE TITLE
manual downloading is annoying

### ISSUE THREAD

**Issue by kuivi** [CliDyn/climsight#75]
we need to figure out what to do with :
WPP2022_Demographic_Indicators_Medium.zip  - can not be downloaded most of the time (some server issues)
and Disaster Location Centroids   (manual downloading is annoying)

_Originally posted by @kuivi in https://github.com/koldunovn/climsight/pull/69#discussion_r1587225878_

**Comment by koldunovn** [comment]
Please have a look at the data licenses. if we can redistribute them - let's put somewere on DKRZ>

**Comment by kuivi** [comment]
**WPP2022_Demographic_Indicators_Medium**  has Creative Commons license CC BY 3.0 IGO: http://creativecommons.org/licenses/by/3.0/igo/ . Means we can upload and redistribute data. However,  we must give appropriate credit ( Suggested citation): United Nations, Department of Economic and Social Affairs, Population Division (2022). World Population Prospects 2022, Online Edition. 
question is where we can show the citation ? 
maybe during downloading ? and after the request to LLM?

**Comment by koldunovn** [comment]
We can have README file next to the data with citation. We also can have a section on the climsight frontend, with all the data listed with proper credits. I would form this page automatically, dependind on what data are used for this particular installation of climsight.

**Comment by kuivi** [comment]
WPP2022_Demographic_Indicators_Medium.zip is on dkrz now (temporal link for 3650 days)
pend-gdis-1960-2018-disasterlocations.csv is on dkrz now (temporal link for 3650 days)
citations added to the yml and, text files next to data files
